Repository UCR-Solar-Car/solarcar-website, pull requests merged in 2022-12, with the labels that each got.

#15 Adopt a Cell Page
  components/AdoptGrid.jsx
  components/AdoptInput.jsx
  components/AdoptText.jsx
  components/Header.jsx
  pages/about.js
  pages/adopt.js
  pages/links.js
  pages/recruitment.js
  pages/resources.js
  pages/sponsors.js
  pages/team.js
Labels: ready for review, Adopt a Cell

#14 add header
  components/Header.jsx
  pages/about.js
  pages/links.js
  pages/recruitment.js
  pages/resources.js
  pages/sponsors.js
  pages/team.js
Labels: ready for review

#18 Sponsors Page
  components/SponsorOutreach.jsx
  components/Sponsors.jsx
  pages/sponsors.js
Labels: ready for review, Sponsors

#20 GCP dev enviornment
  Dockerfile
  README.md
  cloudbuild.yaml
Labels: ready for review

#21 Resources Page
  components/Event.jsx
  components/Events.jsx
Labels: ready for review, Resources

#27 create project managers
  components/ProjectManager.jsx
  components/ProjectManagers.jsx
  public/David.jpg
  public/Leen.jpg
Labels: ready for review, Home

#36 Added core values section
  components/CoreValues.jsx
  components/Header.jsx
  public/BackLeftRender 1.png
  public/BackLeftTransparent 1.png
  public/Battery 1.png
  public/Chassis 1.png
  public/Motor 1.png
  public/SolarArray 1.png
Labels: ready for review

#37 Added layout components for all teams
  .gitignore
  components/Team.jsx
  components/Teams.jsx
Labels: ready for review, Team

#39 finished introduction page
  components/Introduction.jsx
Labels: ready for review

#40 Finished Footer
  components/Footer.jsx
Labels: ready for review

#42 fire
  firebase.js
Labels: ready for review

#43 fix nav
  components/Navigation.jsx
Labels: ready for review

#45 Mgolw001/leads
  components/Lead.jsx
  components/Leads.jsx
Labels: ready for review, Team

#63 Intro Page
  components/Introduction.jsx
  public/GroupPhoto.png
Labels: Home

#75 leads updated
  components/Lead.jsx
  components/Leads.jsx
  public/Daisy.jpg
  public/Divyank.jpg
  public/Esmeralda.jpg
  public/Hallie.jpg
  public/Karam.jpg
  public/Kiana.jpg
  public/Patrick.jpg
  public/Sunny.jpg
  public/temp.png
Labels: ready for review, Team

#79 Clean up read me by Jason Lin
  README.md
Labels: ready for review, Repository

#81 Safeduck/teamMembers
  components/Teams.jsx
Labels: ready for review, Team

#82 cleaned up corevalues
  components/CoreValues.jsx
Labels: ready for review

#92 About Page Paragraph/Image
  components/AboutParagraph.jsx
Labels: ready for review

#94 Migrate to v13
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  tailwind.config.js
Labels: ready for review, Repository

#95 Alternate Link Colors
  components/Link.jsx
  components/Links.jsx
Labels: ready for review

#96 Mgolw001/subteams
  components/Subteam.jsx
  components/Subteams.jsx
Labels: ready for review, Recruitment

#97 Social media icons open in new tab
  components/Footer.jsx
Labels: ready for review, Footer

#103 cleaned up duplicates
  components/Teams.jsx
Labels: ready for review

#104 added spacing
  components/Lead.jsx
Labels: ready for review

#105 body font bigger
  components/Subteam.jsx
Labels: ready for review, Recruitment

#107 Added space between Leads and team, switched order, added member
  components/Leads.jsx
  components/Teams.jsx
Labels: ready for review, Team

#111 Removed team member from Electrical
  components/Teams.jsx
Labels: ready for review, Team

#114 Add Introduction Content for Recruitment
  components/Recruitment.jsx
  pages/recruitment.js
Labels: ready for review, Recruitment

#117 About Tiles
  .eslintrc.json
  components/AboutTiles.jsx
  components/Introduction.jsx
Labels: ready for review, About
