Repository UCR-Solar-Car/solarcar-website, pull requests merged in 2023-02, with the labels that each got.

#220 combine react-icons/fa
  components/Footer.jsx
  package-lock.json
Labels: Footer

#219 Mgolwalla/faq
  components/FAQ.jsx
  components/ProjectManager.jsx
  components/ProjectManagers.jsx
  pages/index.js
Labels: ready for review, Home

#223 Deploy to Github Pages
  .github/workflows/nextjs.yml
Labels: Repository
