Repository UCR-Solar-Car/solarcar-website, pull requests merged in 2023-01, with the labels that each got.

#121 Mgolwalla/subteam header
  components/Event.jsx
  components/Subteam.jsx
  components/Subteams.jsx
Labels: ready for review, Recruitment

#122 Hover buttons on recruitment page
  components/Recruitment.jsx
Labels: ready for review, Recruitment

#123 Statements
  components/ProjectManagers.jsx
Labels: ready for review

#132 corevaluesstyling
  components/CoreValues.jsx
Labels: ready for review, Home

#135 something
  components/Header.jsx
  components/SponsorOutreach.jsx
  pages/links.js
  pages/team.js
Labels: ready for review

#148 Add involvement page
  components/Clubroom.jsx
  components/Organization.jsx
  pages/involvement.js
Labels: ready for review, Join

#159 Button animation centered for Recruitment Page
  components/Recruitment.jsx
Labels: ready for review, Recruitment

#160 add CalendarIntro into recruitment page.
  components/CalendarIntro.jsx
  pages/recruitment.js
Labels: ready for review, Recruitment

#164 deploy
  .github/workflows/main.yaml
  build_dev.sh
  build_main.sh
  package.json
Labels: ready for review

#165 Updated margin
  components/AboutParagraph.jsx
Labels: ready for review

#166 Clubroom component
  components/Clubroom.jsx
Labels: ready for review

#172 Fixed hover colors for learn more button
  components/Introduction.jsx
Labels: ready for review, Home

#174 Unified width of components for core values
  components/CoreValues.jsx
Labels: ready for review, Home

#179 Changed group photo for front page
  components/Introduction.jsx
  public/GroupPhoto.jpg
  public/GroupPhoto.png
Labels: ready for review, Home

#180 create club info in organization and involvement page.
  components/Organization.jsx
  pages/involvement.js
  public/WINC.png
Labels: ready for review, Join

#182 Moved teams/leads arrays to new directory called data
  components/Leads.jsx
  components/Teams.jsx
  components/data/leads.js
  components/data/teams.js
Labels: ready for review, Team
